package project;

import java.util.Random;

public class RandomValues {
	private static final String[] firstNames = new String[50];
	private static final String[] lastNames = new String[20];
	private static final String[] domains = new String[140];	
	private static final Random rand = new Random();
	
	public static String getAFirstName() {
		return firstNames[rand.nextInt(firstNames.length)];
	}
	
	public static String getALastName() {
		return lastNames[rand.nextInt(lastNames.length)];
	}

	public static String getADomain() {
		return domains[rand.nextInt(domains.length)];
	}

	static {		
		firstNames[0] = "Blanche";
		firstNames[1] = "Fatima";
		firstNames[2] = "Rosanne";
		firstNames[3] = "Larraine";
		firstNames[4] = "Lavina";
		firstNames[5] = "Bo";
		firstNames[6] = "Rachel";
		firstNames[7] = "Deidra";
		firstNames[8] = "Russ";
		firstNames[9] = "Gennie";
		firstNames[10] = "Bea";
		firstNames[11] = "Rosia";
		firstNames[12] = "Ann";
		firstNames[13] = "Rachele";
		firstNames[14] = "Hilary";
		firstNames[15] = "Santos";
		firstNames[16] = "Ethelyn";
		firstNames[17] = "Hobert";
		firstNames[18] = "Gil";
		firstNames[19] = "Darci";
		firstNames[20] = "Ming";
		firstNames[21] = "Velva";
		firstNames[22] = "Casey";
		firstNames[23] = "Johanna";
		firstNames[24] = "Ferne";
		firstNames[25] = "Collette";
		firstNames[26] = "Beckie";
		firstNames[27] = "Chieko";
		firstNames[28] = "Janene";
		firstNames[29] = "Graham";
		firstNames[30] = "Maurita";
		firstNames[31] = "Melba";
		firstNames[32] = "Veronika";
		firstNames[33] = "Consuela";
		firstNames[34] = "Lyndsey";
		firstNames[35] = "Yoshie";
		firstNames[36] = "Coralee";
		firstNames[37] = "Kurtis";
		firstNames[38] = "Edie";
		firstNames[39] = "Jenine";
		firstNames[40] = "Mack";
		firstNames[41] = "Suzi";
		firstNames[42] = "Karoline";
		firstNames[43] = "Kaye";
		firstNames[44] = "Jalisa";
		firstNames[45] = "Launa";
		firstNames[46] = "Harmony";
		firstNames[47] = "Ouida";
		firstNames[48] = "Edna";
		firstNames[49] = "Dayna";

		lastNames[0] = "Smith";
		lastNames[1] = "Johnson";
		lastNames[2] = "Williams";
		lastNames[3] = "Brown";
		lastNames[4] = "Jones";
		lastNames[5] = "Miller";
		lastNames[6] = "Davis";
		lastNames[7] = "Garcia";
		lastNames[8] = "Rodriguez";
		lastNames[9] = "Wilson";
		lastNames[10] = "Martinez";
		lastNames[11] = "Anderson";
		lastNames[12] = "Taylor";
		lastNames[13] = "Thomas";
		lastNames[14] = "Hernandez";
		lastNames[15] = "Moore";
		lastNames[16] = "Martin";
		lastNames[17] = "Jackson";
		lastNames[18] = "Thompson";
		lastNames[19] = "White";

		domains[0] = "webmagnat.ro";
		domains[1] = "nickelfreesolutions.com";
		domains[2] = "scheepvaarttelefoongids.nl";
		domains[3] = "tursan.net";
		domains[4] = "plannersanonymous.com";
		domains[5] = "doing.fr";
		domains[6] = "saltstack.com";
		domains[7] = "deconsquad.com";
		domains[8] = "migom.com";
		domains[9] = "tjprc.org";
		domains[10] = "worklife.dk";
		domains[11] = "inno-make.com";
		domains[12] = "food-hub.org";
		domains[13] = "bikemastertool.com";
		domains[14] = "betenbewegen.de";
		domains[15] = "vk.me";
		domains[16] = "twotigersports.com";
		domains[17] = "517mrt.com";
		domains[18] = "siel.nl";
		domains[19] = "e-hps.com";
		domains[20] = "infowheel.com";
		domains[21] = "synirc.net";
		domains[22] = "abuliyan.com";
		domains[23] = "easy-ways.com";
		domains[24] = "stark.dk";
		domains[25] = "funwirks.com";
		domains[26] = "eurocqs.net";
		domains[27] = "202yx.com";
		domains[28] = "nikko-sake.com";
		domains[29] = "xnet.lv";
		domains[30] = "visionpharma.com";
		domains[31] = "trade-india.com";
		domains[32] = "t-bird.edu";
		domains[33] = "siebel-crm.net";
		domains[34] = "adriaticapress.it";
		domains[35] = "41789.com";
		domains[36] = "autofirenze.biz";
		domains[37] = "minniowa.com";
		domains[38] = "sweetteaproper.com";
		domains[39] = "recruit-dc.co.jp";
		domains[40] = "competitivecameras.com";
		domains[41] = "zoncinta.com";
		domains[42] = "vadim-prostakov.ru";
		domains[43] = "vk.me";
		domains[44] = "securitasweb.it";
		domains[45] = "mandarinclass.my";
		domains[46] = "pbxi.net";
		domains[47] = "zyznowski.pl";
		domains[48] = "meodia.com";
		domains[49] = "niceinternetmoney.ru";
		domains[50] = "guardiancaps.com";
		domains[51] = "bbccable.net";
		domains[52] = "ams-luenen.de";
		domains[53] = "ihalehaberbulteni.com";
		domains[54] = "salvia-community.net";
		domains[55] = "superpowerfruits.com";
		domains[56] = "bereyellingergl.com";
		domains[57] = "downloadfreetvseries.com";
		domains[58] = "iqshop.ro";
		domains[59] = "urbancliq.com";
		domains[60] = "rocket-media.net";
		domains[61] = "uskudarhaliyikama.org";
		domains[62] = "ftbp.ro";
		domains[63] = "savedeo.com";
		domains[64] = "nanabit.net";
		domains[65] = "memewood.com";
		domains[66] = "divorcereform.us";
		domains[67] = "solarincomefund.com";
		domains[68] = "novofri.com";
		domains[69] = "8852088.com";
		domains[70] = "admil.ru";
		domains[71] = "rafonline.org";
		domains[72] = "bois-francs.com";
		domains[73] = "pieceinch.com";
		domains[74] = "tel.com";
		domains[75] = "teenpregnancysc.org";
		domains[76] = "wisdomforhealth.net";
		domains[77] = "powgnar.com";
		domains[78] = "screenmediamag.com";
		domains[79] = "pricerabbit.com";
		domains[80] = "archive-host.fr";
		domains[81] = "hotimpit.ru";
		domains[82] = "detskie-krovatki.by";
		domains[83] = "3sitracking.com";
		domains[84] = "hellfiremods.co.uk";
		domains[85] = "eslyoga.com";
		domains[86] = "buyphen375cheap.com";
		domains[87] = "kilgour.com";
		domains[88] = "vk.me";
		domains[89] = "hualienhouse.com";
		domains[90] = "tour-box.ru";
		domains[91] = "servizioallerta.it";
		domains[92] = "denyojp.com";
		domains[93] = "2912muranoway.info";
		domains[94] = "centralepiecesauto.com";
		domains[95] = "bluedynamics.com";
		domains[96] = "xjs123.com";
		domains[97] = "veryicon.com";
		domains[98] = "emrekoldas.com";
		domains[99] = "adc-inspect.com";
		domains[100] = "vusadbe.by";
		domains[101] = "morban.co.uk";
		domains[102] = "hainanair.us";
		domains[103] = "vk.me";
		domains[104] = "metar.gr";
		domains[105] = "reviewsearchfree.com";
		domains[106] = "treasureislandbar.com";
		domains[107] = "mobilier-bebe.com";
		domains[108] = "bvillaseminyak.com";
		domains[109] = "sponsoredhomepage.com";
		domains[110] = "santifortwo.com";
		domains[111] = "pcrecruiter.net";
		domains[112] = "bcdtofu.com";
		domains[113] = "thefavorite.fr";
		domains[114] = "aneventapart.com";
		domains[115] = "pces.in";
		domains[116] = "alamelphan.com";
		domains[117] = "hotel63.com";
		domains[118] = "kitubi.com";
		domains[119] = "zenrog.com";
		domains[120] = "kinderroller.org";
		domains[121] = "naverisk.com";
		domains[122] = "teme.us";
		domains[123] = "tlinkbroadband.com";
		domains[124] = "de.vc";
		domains[125] = "rivnetwork.com";
		domains[126] = "bufobufo.eu";
		domains[127] = "friatider.se";
		domains[128] = "mannllc.com";
		domains[129] = "rideukbmx.com";
		domains[130] = "agnx.com";
		domains[131] = "stackablehost.com";
		domains[132] = "muzed.co.uk";
		domains[133] = "up247.me";
		domains[134] = "vk.com";
		domains[135] = "urt.is";
		domains[136] = "notabilus.com";
		domains[137] = "jordansun.com";
		domains[138] = "frosta.hu";
		domains[139] = "lacuisinedegandi.net";

	}
}
